name: CI
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install tensorflow.js
        run: 
          pip install tensorflowjs

      - name: Convert models to tfjs
        run: ls -d policy_models/*/*/*/ | xargs -I"{}" tensorflowjs_converter --input_format=tf_saved_model --output_node_names='parkour_walker' --saved_model_tags=serve --skip_op_check {}tf1_save web_demo/{}

      - name: Generate the list of models
        run:
          python3 policies_to_json.py
          
      - name: Generate the list of base environments filenames
        run:
          python3 list_base_envs.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./web_demo
